version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    depends_on:
      - db
    command: flask run --host=0.0.0.0

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=million
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: